Better error message on unexpected secret source
Co-authored-by: Giovanni Toraldo <71768+gionn@users.noreply.github.com>

diff --git a/.github/actions/github-check-secrets-source/action.yml b/.github/actions/github-check-secrets-source/action.yml
--- a/.github/actions/github-check-secrets-source/action.yml
+++ b/.github/actions/github-check-secrets-source/action.yml
@@ -15,5 +15,5 @@ runs:
         fi
         if [[ $SECRET_SOURCE != 'Actions' && $SECRET_SOURCE != 'Codespaces' ]]
         then
-          echo "::error::Missing proper secrets source: failing build" && exit 1
+          echo "::error::Unexpected $SECRET_SOURCE secrets source: failing build" && exit 1
         fi
