adjust error messages

diff --git a/.github/actions/github-require-secrets/action.yml b/.github/actions/github-require-secrets/action.yml
--- a/.github/actions/github-require-secrets/action.yml
+++ b/.github/actions/github-require-secrets/action.yml
@@ -2,10 +2,14 @@ name: Require Secrets for Github Actions
 description: Fails if secrets source is not valid for the workflow run
 
 inputs:
-  error-message:
-    description: 'Error message to show when secrets source is invalid because of Dependabot or forks'
+  dependabot-error-message:
+    description: 'Error message to show when secrets source is invalid because of Dependabot'
     required: false
-    default: 'Access to secrets forbidden: follow your repository process for PR validation'
+    default: 'Access to secrets forbidden for Dependabot: follow your repository process for PR validation'
+  none-error-message:
+    description: 'Error message to show when secrets source is None (fork use case)'
+    required: false
+    default: 'Access to secrets forbidden'
 
 runs:
   using: composite
@@ -13,14 +17,20 @@ runs:
     - name: Check secret source
       env:
         SECRET_SOURCE: ${{ github.secret_source }}
-        ERROR_MESSAGE: ${{ inputs.error-message }}
       shell: bash
       run: |
-        if [[ $SECRET_SOURCE == 'Dependabot' || $SECRET_SOURCE == 'None' ]]
+        if [[ "$SECRET_SOURCE" == "Dependabot" ]]
         then
-          echo "::error::$ERROR_MESSAGE" && exit 1
+          echo "::error::${{ inputs.dependabot-error-message }}"
+          exit 1
+        elif [[ "$SECRET_SOURCE" == "None" ]]
+        then
+          echo "::error::${{ inputs.none-error-message }}"
+          exit 1
         fi
-        if [[ $SECRET_SOURCE != 'Actions' && $SECRET_SOURCE != 'Codespaces' ]]
+
+        if [[ "$SECRET_SOURCE" != "Actions" && "$SECRET_SOURCE" != "Codespaces" ]]
         then
-          echo "::error::Unexpected secrets source '$SECRET_SOURCE': failing build" && exit 1
+          echo "::error::Unexpected secrets source '$SECRET_SOURCE' (expected 'Actions' or 'Codespaces'): failing build"
+          exit 1
         fi
