review

diff --git a/.github/actions/nuxeo/nuxeo-docker-build/action.yml b/.github/actions/nuxeo/nuxeo-docker-build/action.yml
--- a/.github/actions/nuxeo/nuxeo-docker-build/action.yml
+++ b/.github/actions/nuxeo/nuxeo-docker-build/action.yml
@@ -94,13 +94,18 @@ runs:
         echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
         echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
 
-    - name: Ensure addons directory exists
+    - name: Ensure local nuxeo modules directory exists
+      env:
+        EMPTY_DIR: /tmp/empty_addons
       shell: bash
       run: |
         ADDONS_DIR='${{ inputs.nuxeo-local-modules-path }}'
         if [ ! -d "$ADDONS_DIR" ]; then
           echo "Local addons directory '$ADDONS_DIR' not found. Creating empty directory." >&2
-          mkdir -p "$ADDONS_DIR"
+          mkdir -p ${{ env.EMPTY_DIR }}
+          echo "NUXEO_LOCAL_MODULES_PATH=${{ env.EMPTY_DIR }}" >> $GITHUB_ENV
+        else
+          echo "NUXEO_LOCAL_MODULES_PATH=$ADDONS_DIR" >> $GITHUB_ENV
         fi
 
     - name: Login to base image registry
@@ -110,11 +115,21 @@ runs:
         username: ${{ inputs.base-registry-username }}
         password: ${{ inputs.base-registry-password }}
 
+    - name: Check if credentials to target registry are provided when pushing image
+      if: ${{ inputs.push-image == 'true' }}
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.registry-username }}" ] || [ -z "${{ inputs.registry-password }}" ]; then
+          echo "Error: registry-username and registry-password inputs are required when push-image is true." >&2
+          exit 1
+        fi
+
     - name: Login to target registry
+      if: ${{ inputs.push-image == 'true' }}
       uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
       with:
         registry: ${{ inputs.registry }}
-        username: ${{ inputs.registry-username || github.actor }}
+        username: ${{ inputs.registry-username }}
         password: ${{ inputs.registry-password }}
 
     - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
@@ -129,7 +144,7 @@ runs:
       with:
         context: ${{ github.action_path }}
         build-contexts: |
-          modules=${{ github.workspace }}/${{ inputs.nuxeo-local-modules-path }}
+          modules=${{ github.workspace }}/${{ env.NUXEO_LOCAL_MODULES_PATH }}
         push: ${{ inputs.push-image }}
         platforms: ${{ inputs.platforms }}
         provenance: false
