add support for .sdkmanrc and maven build cache extension

diff --git a/.github/actions/maven-build-and-tag/action.yml b/.github/actions/maven-build-and-tag/action.yml
--- a/.github/actions/maven-build-and-tag/action.yml
+++ b/.github/actions/maven-build-and-tag/action.yml
@@ -9,6 +9,14 @@ inputs:
     description: The Java distribution to perform the build
     required: false
     default: 'temurin'
+  use-sdkman:
+    description: Use SDKMAN! to setup CI environment.
+    required: false
+    default: 'false'
+  build-cache-key:
+    description: The build cache key to use
+    required: false
+    default: ''
   property-to-update:
     description: Property to update in addition to the version of the pom file
     required: false
@@ -88,11 +96,35 @@ runs:
         restore-keys: |
           ${{ runner.os }}-maven-
 
+    - uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
+      if: inputs.build-cache-key != ''
+      with:
+        path: ~/.m2/build-cache
+        key: ${{ runner.os }}-build-cache-${{ inputs.build-cache-key }}
+
     - name: Set up JDK
-      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
+      if: inputs.use-sdkman == 'false'
+      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
       with:
         java-version: ${{ inputs.java-version }}
         distribution: ${{ inputs.java-distribution }}
+
+    - name: Set up SDKMAN!
+      if: inputs.use-sdkman == 'true'
+      id: sdkman
+      shell: bash
+      run: |
+        if ! [[ -f '.sdkmanrc' ]]; then
+          echo ".sdkmanrc is required for SDKMAN! setup."
+          exit 1
+        fi
+        export SDKMAN_DIR="$HOME/.sdkman" && curl -s "https://get.sdkman.io?rcupdate=false" | bash
+        source $HOME/.sdkman/bin/sdkman-init.sh && sdk env install
+        for child_dir in $(find "$SDKMAN_DIR/candidates" -mindepth 1 -maxdepth 1 -type d); do
+          echo "$child_dir/current/bin" >> $GITHUB_PATH
+        done
+        sdk env
+
 
     - name: Compute maven options
       id: compute-maven-options
@@ -252,3 +284,10 @@ runs:
       with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+
+    - name: Save maven build cache
+      uses: actions/cache/save@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
+      if: success() && inputs.build-cache-key != ''
+      with:
+        path: ~/.m2/build-cache
+        key: ${{ runner.os }}-build-cache-${{ inputs.build-cache-key }}
