support for plan when explicitly requested

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -108,6 +108,16 @@ jobs:
       # https://github.com/dflook/terraform-github-actions/tree/main/terraform-apply#applying-a-plan-using-a-comment
       PR_CHECKOUT_REF: refs/pull/${{ github.event.issue.number }}/merge
     steps:
+      - name: Check inputs
+        run: |
+          case "${{ inputs.terraform_operation }}" in
+            apply|destroy|plan)
+              ;;
+            *)
+              echo "Invalid terraform_operation: ${{ inputs.terraform_operation }}. Must be 'apply', 'destroy', or 'plan'."
+              exit 1
+              ;;
+          esac
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -166,7 +176,7 @@ jobs:
 
       - name: Terraform plan
         uses: dflook/terraform-plan@b7bf0aabcffd1699464b3ef10c9bff6b265231c0 # v2.1.0
-        if: github.event_name == 'pull_request'
+        if: github.event_name == 'pull_request' || inputs.terraform_operation == 'plan'
         with:
           label: ${{ vars.RESOURCE_NAME }} ${{ inputs.terraform_root_path }}
           path: ${{ inputs.terraform_root_path }}
