verify installation

diff --git a/.github/workflows/test-nuxeo.yml b/.github/workflows/test-nuxeo.yml
--- a/.github/workflows/test-nuxeo.yml
+++ b/.github/workflows/test-nuxeo.yml
@@ -10,47 +10,41 @@ on:
 
 jobs:
   test:
+    env:
+      NUXEO_CONNECT_MODULE: nuxeo-web-ui
+      NUXEO_LOCAL_MODULE: nuxeo-ai-image-quality-package
+      NUXEO_LOCAL_MODULES_PATH: addons
+      NUXEO_OS_PACKAGES: |
+        awscli
+        ccextractor-nuxeo
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
 
       - name: Prepare addons directory
         shell: bash
-        run: mkdir -p addons
+        run: mkdir -p ${{ env.NUXEO_LOCAL_MODULES_PATH }}
 
       - name: Fetch Nuxeo local module
         shell: bash
         env:
-          PKG_URL: https://packages.nuxeo.com/repository/maven-public-releases/org/nuxeo/ai/nuxeo-ai-image-quality-package/4.0.2/nuxeo-ai-image-quality-package-4.0.2.zip
+          PKG_URL: https://packages.nuxeo.com/repository/maven-public-releases/org/nuxeo/ai/${{ env.NUXEO_LOCAL_MODULE }}/4.0.2/${{ env.NUXEO_LOCAL_MODULE }}-4.0.2.zip
           NEXUS_USER: ${{ secrets.NUXEO_NEXUS_USER }}
           NEXUS_TOKEN: ${{ secrets.NUXEO_NEXUS_PASSWORD }}
         run: |
-          curl -fsSL -u "$NEXUS_USER:$NEXUS_TOKEN" "$PKG_URL" -o addons/nuxeo-ai-image-quality-package-4.0.2.zip;
-          test -s addons/nuxeo-ai-image-quality-package-4.0.2.zip
+          curl -fsSL -u "$NEXUS_USER:$NEXUS_TOKEN" "$PKG_URL" -o ${{ env.NUXEO_LOCAL_MODULES_PATH }}/${{ env.NUXEO_LOCAL_MODULE }}-4.0.2.zip;
+          test -s ${{ env.NUXEO_LOCAL_MODULES_PATH }}/${{ env.NUXEO_LOCAL_MODULE }}-4.0.2.zip
 
       - name: Build nuxeo image and push to registry
         uses: ./.github/actions/nuxeo/nuxeo-docker-build
+        id: build_nuxeo_image
         with:
           base-registry-username: ${{ secrets.NUXEO_NEXUS_USER }}
           base-registry-password: ${{ secrets.NUXEO_NEXUS_PASSWORD }}
-          nuxeo-connect-modules: nuxeo-web-ui
+          nuxeo-connect-modules: ${{ env.NUXEO_CONNECT_MODULE }}
           nuxeo-clid: ${{ secrets.NUXEO_CLID }}
-          nuxeo-local-modules-path: addons
-          os-packages: |
-            awscli
-            ghostscript
-            libwpd-tools
-            perl-Archive-Zip
-            perl-Image-ExifTool
-            poppler-utils
-            libreoffice-calc
-            libreoffice-headless
-            libreoffice-impress
-            curl
-            unzip
-            zip
-            ffmpeg-nuxeo
-            ccextractor-nuxeo
+          nuxeo-local-modules-path: ${{ env.NUXEO_LOCAL_MODULES_PATH }}
+          os-packages: ${{ env.NUXEO_OS_PACKAGES }}
           os-packages-user: ${{ secrets.NUXEO_NEXUS_USER }}
           os-packages-token: ${{ secrets.NUXEO_NEXUS_PASSWORD }}
           image-name: nuxeo/nuxeo-ci-builder-test
@@ -58,3 +52,44 @@ jobs:
           image-title: "Nuxeo CI Builder Test"
           load-image: "true"
           platforms: linux/amd64 # load can only be done for a single platform
+          registry: localhost
+
+      - name: Verify installed Nuxeo Modules
+        shell: bash
+        run: |
+          IMAGE_URL=${{ steps.build_nuxeo_image.outputs.image-url }}
+
+          MP_LIST_OUTPUT=$(docker run --rm $IMAGE_URL bash -lc 'nuxeoctl mp-list')
+
+          echo "--- nuxeoctl mp-list output ---"
+          echo "$MP_LIST_OUTPUT"
+          echo "------------------------------"
+
+          if echo "$MP_LIST_OUTPUT" | grep -q "${{ env.NUXEO_CONNECT_MODULE}}"; then
+            echo "✅ connect module found."
+          else
+            echo "❌ connect module NOT found."
+            exit 1
+          fi
+
+          if echo "$MP_LIST_OUTPUT" | grep -q "${{ env.NUXEO_LOCAL_MODULE}}"; then
+            echo "✅ local module found."
+          else
+            echo "❌ local module NOT found."
+            exit 1
+          fi
+
+          INSTALLED_PACKAGES_OUTPUT=$(docker run --rm $IMAGE_URL bash -lc 'rpm -qa')
+
+          echo "--- Installed OS packages ---"
+          echo "$INSTALLED_PACKAGES_OUTPUT"
+          echo "-----------------------------"
+
+          for pkg in $(echo "${{ env.NUXEO_OS_PACKAGES }}"); do
+            if echo "$INSTALLED_PACKAGES_OUTPUT" | grep -q "^${pkg}"; then
+              echo "✅ OS package '$pkg' found."
+            else
+              echo "❌ OS package '$pkg' NOT found."
+              exit 1
+            fi
+          done
